version: '3.8'

services:
  webserver:
    image: nginx
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

  frontend:
    image: plone/plone-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://backend:8080/Plone
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: plone/plone-backend:6.1
    environment:
      SITE: Plone
      RELSTORAGE_DSN: "dbname='plone' user='plone' host='db' password='plone'"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: plone
      POSTGRES_PASSWORD: plone
      POSTGRES_DB: plone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: